### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getSinglePermissionStatus on channel plugins.ly.com/permission)

### ISSUE THREAD

**Issue by luckymehndiratta** [once10301/permission#40]
i face this 
Unhandled Exception: MissingPluginException(No implementation found for method getSinglePermissionStatus on channel plugins.ly.com/permission)

**Comment by kxait** [comment]
same here

**Comment by Naveenkumar3506** [comment]
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getPermissionsStatus on channel plugins.ly.com/permission)

**Comment by maelfosso** [comment]
I also have the same issue
```dart
E/flutter (30581): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getSinglePermissionStatus on channel plugins.ly.com/permission)
E/flutter (30581): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (30581): <asynchronous suspension>
E/flutter (30581): #1      Permission.getSinglePermissionStatus (package:permission/permission.dart:40:32)
E/flutter (30581): #2      _HomePageState.requestWritePermission (package:guitou/pages/home_page.dart:75:45)
E/flutter (30581): #3      _HomePageState.initState (package:guitou/pages/home_page.dart:60:5)
E/flutter (30581): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter (30581): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (30581): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (30581): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (30581): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (30581): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (30581): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (30581): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (30581): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (30581): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (30581): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (30581): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (30581): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (30581): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (30581): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (30581): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (30581): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (30581): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (30581): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (30581): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (30581): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (30581): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (30581): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (30581): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (30581): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (30581): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (30581): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (30581): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (30581): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (30581): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (30581): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (30581): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (30581): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (30581): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (30581): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (30581): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (30581): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (30581): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (30581): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (30581): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (30581): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3947
I/flutter (30581): 
```

**Comment by pockyzhang** [comment]
same here

**Comment by pockyzhang** [comment]
seems request permission in initState fails

**Comment by CurtesMalteser** [comment]
Same here. Any alternatives?

**Comment by Lomba8** [comment]
Same here:
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getSinglePermissionStatus on channel plugins.ly.com/permission)
#0      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:154
<asynchronous suspension>
#1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:329
#2      Permission.getSinglePermissionStatus 
package:permission/permission.dart:40
#3      _OrariSectionState.build.<anonymous closure> 
package:Messedaglia/…/orari_section/orari_section.dart:128
#4      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:779
#5      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:862
#6      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
#7      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:504
#8      BaseTapGestureRecognizer._c<…>

**Comment by avvari-da** [comment]
Do this - https://github.com/once10301/permission/issues/28#issuecomment-484062708
Not changing to `getSinglePermissionStatus`, but to switch to https://pub.dartlang.org/packages/permission_handler

**Comment by ole1986** [comment]
Can this not be resolved by doing a simple `flutter clean`?

**Comment by kungsoft** [comment]
E/flutter ( 4104): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getSinglePermissionStatus on channel plugins.ly.com/permission)

**Comment by DSenanayake** [comment]
Same 👎

**Comment by XenonChau** [comment]
![image](https://user-images.githubusercontent.com/11521664/82871102-98103880-9f63-11ea-8f27-f251d29f048f.png)
Author was not implemented it yet.(why publish it to pub?)

**Comment by pavelsust** [comment]
same problem facing

**Comment by ramin443** [comment]
Instead of using the Permission.getsinglepermission, use Permission.getPermissionsStatus like:
`
List<PermissionName> permissionnames=[PermissionName.Storage];

await Permission.getPermissionsStatus(permissionNames);
`
This solved the issue in my case

**Comment by myselfuser1** [comment]
This might help https://www.youtube.com/watch?v=uMvGpBOT0ZY
